# Generated by Django 4.1.5 on 2023-03-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_url', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('platform', models.CharField(max_length=70)),
                ('developer', models.CharField(max_length=50)),
                ('date_release', models.CharField(max_length=10)),
                ('img', models.TextField()),
                ('trailer', models.TextField()),
                ('val', models.FloatField()),
            ],
        ),
    ]
